name: Process multiple config templates

on:
  workflow_call:
inputs:
  working_directory:
    description: 'Working directory for this action, defaults to the current worker directory'
    required: false
    default: "."
  env_variables:
    description: 'JSON string object with information about variables and mappings. See more in the documentation.'
    required: true

runs:
  using: 'node24'
  main: 'index.js'
