name: Prepare environment consisting of multiple configs

inputs:
  working_directory:
    description: 'Working directory for this action, defaults to the current worker directory'
    required: false
    default: "."
  env_variables:
    description: 'JSON string object with information about variables and mappings. See more in the documentation.'
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get environment configs
      id: config-list
      run: |
        echo "Reading configs from ${{ inputs.working_directory }}/_ci_environment.json"
        configs=$(jq -c '.config[]' "${{ inputs.working_directory }}/_ci_environment.json")
        echo "configs<<EOF" >> $GITHUB_OUTPUT
        echo "$configs" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT


    - name: Process configs
      uses: uniquesca/ci/prepare-config@feature/multiple-configs
      with:
        working_directory: ${{ inputs.working_directory }}
        env_file_stub: ${{ fromJson(matrix.config).stub }}
        env_file: ${{ fromJson(matrix.config).path }}
        env_variables: ${{ inputs.env_variables }}
      strategy:
        matrix:
          config: ${{ steps.config-list.outputs.configs }}
