name: Inject version into composer.json

inputs:
  working_directory:
    description: 'Directory containing composer.json'
    required: false
    type: string
    default: '.'
  version:
    description: 'Version to inject into composer.json'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set Composer version from Git tag
      working-directory: ${{ inputs.working_directory }}
      run: |
        VERSION="${{ inputs.version }}"
        echo "Setting version in composer.json to $VERSION"

        if jq -e '.version' composer.json > /dev/null; then
          echo "Version found in composer.json. Updating version."
          jq --arg version "$VERSION" '.version = $version' composer.json > composer.tmp.json && mv composer.tmp.json composer.json
        else
          echo '"version" not found in composer.json. Adding version field'
          jq --arg version "$VERSION" '. + {version: $version}' composer.json > composer.tmp.json && mv composer.tmp.json composer.json
        fi
