name: Inject version into composer.json

inputs:
  github_ref:
    description: 'Ref to get version from'
    required: true
    type: string
  working_directory:
    description: 'Directory containing composer.json'
    required: false
    type: string
    default: '.'

outputs:
  version:
    description: 'Extracted version from Git ref'
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Extract version from ref
      id: get-version
      shell: bash
      run: |
        ref="${{ inputs.github_ref }}"
        if [[ "$ref" =~ ^refs/heads/release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          version="${ref#refs/heads/release/}"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        elif [[ "$ref" =~ ^refs/heads/hotfix/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          version="${ref#refs/heads/hotfix/}"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        else
          echo "Unable to determine version from ref: $ref"
          exit 2
        fi

    - name: Set Composer version in composer.json
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        VERSION="${{ steps.get-version.outputs.version }}"
        echo "Setting version in composer.json to $VERSION"

        if jq -e '.version' composer.json > /dev/null; then
          echo "Version found in composer.json. Updating version."
          jq --arg version "$VERSION" '.version = $version' composer.json > composer.tmp.json && mv composer.tmp.json composer.json
        else
          echo '"version" not found in composer.json. Adding version field'
          jq --arg version "$VERSION" '. + {version: $version}' composer.json > composer.tmp.json && mv composer.tmp.json composer.json
        fi
