name: Update Changelog

inputs:
  working_directory:
    description: 'Path to the directory with changelogs'
    required: false
  target_version:
    description: 'Version to add to the changelog'
    required: true
  mode:
    description: 'Can be "normal" or "raw". Latter one will simply yield changelog with no file normalization'
    required: false
    default: 'normal'
  offset:
    description: 'Offset for the start tag to get changelog since'
    required: false
    default: '0'
  use_tags:
    description: 'Whether to generate changelogs based on tags'
    required: false
    default: true
runs:
  using: 'node24'
  main: 'index.js'
