name: 'check-exec-bit'

inputs:
  paths:
    description: 'Paths to use for checking files for executability, split by comma. Use . (dot) to include 
          root directory. Example: "module, vendor/bin" or "., node_modules"'
    required: false
    default: ''
    type: string
  extensions:
    description: 'File extensions to check for executability, split by comma. Example: "sh, php"'
    required: false
    default: 'sh'
    type: string

runs:
  using: "composite"
  steps:
    - name: Check execution bits
      run: |
        echo "${{ github.workspace }}
        chmod +x ../src/bash-exec.sh
        ../src/bash-exec.sh ${{ github.workspace }} ${{ inputs.paths }} ${{ inputs.extensions }}
      shell: bash
