name: Prepare config

description: Render one config template file with provided variables

inputs:
  working_directory:
    description: 'Working directory for this action, defaults to the current worker directory'
    required: false
    default: "."
  source:
    description: 'Template source file path, relative to working_directory'
    required: true
  destination:
    description: 'Destination file path, relative to working_directory'
    required: true
  variables:
    description: 'JSON object with variables used to render the template'
    required: true

runs:
  using: 'node24'
  main: 'index.js'