name: "[DEPRECATED] Publish GitHub release"
description: "Deprecated: use uniquesca/ci/github-release instead."

inputs:
  release_version:
    description: 'Version being published, has to be in x.y.z format'
    required: true
  attach_dist:
    description: 'Whether a compressed dist folder should be attached to the release'
    required: false
    default: 'false'
  dist_folder:
    description: 'Dist folder to use for publishing. Ignored if attach_dist input is not set to `true`'
    required: false
    default: 'dist'
  repo_token:
    description: 'GitHub access token with the access to publish package in the repository'
    required: true

env:
  FILES: ''

runs:
  using: "composite"
  steps:
    - name: Deprecation notice
      shell: bash
      run: |
        echo "::warning title=Deprecated action::uniquesca/ci/publish-github-release is deprecated. Please migrate to uniquesca/ci/github-release."

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - run: |
        zip -qq -r dist.zip ${{ inputs.dist_folder }}
        echo "FILES=dist.zip" >> "$GITHUB_ENV"
      if: ${{ inputs.attach_dist == 'true' }}
      shell: bash

    - name: Generate changelog for the release
      uses: uniquesca/ci/update-changelog@main
      with:
        mode: 'raw'
        offset: 1
        working_directory: '_github_ci_changelog'
        target_version: ${{ inputs.release_version }}
        use_tags: false

    - name: Shrinking changelog if it's too big
      shell: bash
      working-directory: '_github_ci_changelog'
      run: |
        if [ $(wc -c < CHANGELOG.md) -gt 125000 ]; then
          echo "Github body message has more than 125000 characters, cutting..."
          head -c 124000 CHANGELOG.md > temp.txt && mv temp.txt CHANGELOG.md
          echo "..." >> 'CHANGELOG.md'
        fi

    - name: Debug changelog
      working-directory: '_github_ci_changelog'
      run: cat CHANGELOG.md
      shell: bash

    - uses: softprops/action-gh-release@v3
      with:
        token: ${{ inputs.repo_token }}
        body_path: '_github_ci_changelog/CHANGELOG.md'
        tag_name: ${{ inputs.release_version }}
        prerelease: false
        name: Release ${{ inputs.release_version }}
        files: ${{ env.FILES }}
