name: 'Publish Github Release'

inputs:
  release_version:
    description: 'Version being published, has to be in x.y.z format'
    required: true
  attach_dist:
    description: 'Whether a compressed dist folder should be attached to the release'
    required: false
    default: 'false'
  dist_folder:
    description: 'Dist folder to use for publishing. Ignored if attach_dist input is not set to `true`'
    required: false
    default: 'dist'
  repo_token:
    description: 'GitHub access token with the access to publish package in the repository'
    required: true

env:
  FILES: ''

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: |
        zip -qq -r dist.zip ${{ inputs.dist_folder }}
        echo "FILES=dist.zip" >> "$GITHUB_ENV"
      if: ${{ inputs.attach_dist == 'true' }}
      shell: bash

    - name: Generate changelog for the release
      uses: uniquesca/ci/update-changelog@main
      with:
        mode: 'raw'
        offset: 1
        changelog_path: '_github_ci_changelog.txt'
        target_version: ${{ inputs.release_version }}

    - name: Debug changelog
      run: cat _github_ci_changelog.txt
      shell: bash

    - uses: softprops/action-gh-release@v2
      with:
        token: ${{ inputs.repo_token }}
        body_path: '_github_ci_changelog.txt'
        tag_name: ${{ inputs.release_version }}
        prerelease: false
        name: Release ${{ inputs.release_version }}
        files: ${{ env.FILES }}
