name: 'Publish Github Release'

inputs:
  release_version:
    description: 'Version being published, has to be in x.y.z format'
    required: true
    type: string
  attach_dist:
    description: 'Whether a compressed dist folder should be attached to the release'
    required: false
    type: bool
    default: false
  dist_folder:
    description: 'Dist folder to use for publishing. Ignored if attach_dist input is not set to `true`'
    required: false
    default: 'dist'
    type: string
  repo_token:
    description: 'GitHub access token with the access to publish package in the repository'
    required: true
    type: string

env:
  FILES: ''

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.attach_dist == true }}
      shell: bash
      run: |
        zip -qq -r dist.zip ${{ inputs.dist_folder }}
        echo "FILES=dist.zip" >> "$GITHUB_ENV"

    - uses: softprops/action-gh-release@v1
      with:
        token: ${{ inputs.repo_token }}
        tag_name: ${{ inputs.release_version }}
        prerelease: false
        name: Release ${{ inputs.release_version }}
        files: ${{ env.FILES }}
