name: Install packages (Composer/Yarn/NPM)

inputs:
  access_token:
    description: 'GitHub access token with the access to read from repositories'
    required: false
  composer_update:
    description: 'Will run `composer update` instead of `composer install` if true'
    required: false
    default: false
  skip_composer:
    description: 'Skip Composer installation'
    required: false
    default: false
  composer_install_cmd:
    description: 'Command to install Composer'
    required: false
    default: "composer install --no-scripts"
  composer_update_cmd:
    description: 'Command to update Composer'
    required: false
    default: "composer update --no-scripts"
  composer_cache_dir:
    description: 'Composer cache directory'
    required: false
    default: false
  skip_npm_yarn:
    description: 'Skip NPM/Yarn installation'
    required: false
    default: false
  npm_cache_dir:
    description: 'NPM cache directory'
    required: false
    default: false
  npm_install_cmd:
    description: 'Command to install NPM'
    required: false
    default: "composer install --no-scripts"
  yarn_cache_dir:
    description: 'Yarn cache directory'
    required: false
    default: false
  yarn_install_cmd:
    description: 'Command to install Yarn'
    required: false
    default: "yarn install --production=false"
  cache_key:
    description: 'Cache key fraction to add to make cache unique'
    required: false
    default: ''

runs:
  using: "composite"
  env:
    composer_cache_dir: ${{ inputs.composer_cache_dir }}
    composer_install_cmd: ${{ inputs.composer_install_cmd}}
    npm_cache_dir: ${{ inputs.npm_cache_dir }}
    npm_install_cmd: ${{ inputs.npm_install_cmd }}
    npm_update_cmd: ${{ inputs.npm_update_cmd }}
    yarn_cache_dir: ${{ inputs.yarn_cache_dir }}
    yarn_install_cmd: ${{ inputs.yarn_install_cmd }}
  shell: bash
  steps:
    - name: Check if we have Composer to install
      if: inputs.skip_composer != true
      run: |
        if [[ -f "composer.json" ]]; then
          echo "composer=1" >> $GITHUB_ENV
        else
          echo "No Composer found, skipping."
        fi

    - name: Get Composer Cache Directory
      if: env.composer == 1 && inputs.compose_cache_dir == false
      run: |
        echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

    - name: Cache Composer dependencies
      if: env.composer == 1
      id: cache-composer
      uses: actions/cache@v4
      with:
        path: ${{ env.composer_cache_dir }}
        key: ${{ runner.os }}-${{ inputs.cache_key}}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies (Composer-locked environment)
      if: env.composer == 1 && input.composer_update != true
      run: |
        composer config --auth github-oauth.github.com ${{ inputs.access_token }}
        ${{ env.composer_install_cmd }}

    - name: Update Composer dependencies (not Composer-locked environment)
      if: env.composer == 1 && input.composer_update == true
      run: |
        composer config --auth github-oauth.github.com ${{ inputs.access_token }}
        ${{ env.composer_update_cmd }}

    - name: Check if we have NPM/Yarn to install
      if: inputs.skip_npm_yarn != true
      run: |
        if [[ -f "package.json" ]]; then
          if [ -f ".yarnrc" ]; then
            echo "yarn=1" >> $GITHUB_ENV
          else 
            echo "npm=1" >> $GITHUB_ENV
          fi
        else
          echo "No NPM/Yarn found, skipping JS/TS-related QA."
        fi

    - name: Prepare .npmrc file
      if: env.npm == 1 || env.yarn == 1
      run: |
        echo "@uniquesca:registry=https://npm.pkg.github.com/" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.access_token }}" >> .npmrc

    - name: Get NPM cache directory
      if: env.npm == 1
      run: echo "npm_cache_dir=$(npm config get cache)" >> $GITHUB_ENV

    - name: NPM cache
      if: env.npm == 1
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ${{ env.npm_cache_dir }}
        key: ${{ runner.os }}-${{ inputs.cache_key}}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install NPM dependencies
      if: env.npm == 1
      env:
        NODE_AUTH_TOKEN: ${{ inputs.access_token }}
      run: ${{ env.npm_install_cmd }}

    - name: Get Yarn cache directory
      if: env.yarn == 1
      run: echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Yarn cache
      if: env.yarn == 1
      id: cache-yarn
      uses: actions/cache@v4
      with:
        path: ${{ env.yarn_cache_dir }}
        key: ${{ runner.os }}-${{ inputs.cache_key}}-yarn-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Yarn dependencies
      if: env.yarn == 1
      env:
        NODE_AUTH_TOKEN: ${{ inputs.access_token }}
      run: |
        # This is a hack because otherwise Yarn can't just download private packages =/
        if [ -f "yarn.lock" ]; then
          rm yarn.lock
        fi
        
        ${{ env.yarn_install_cmd }}
