name: 'mysql-export'

inputs:
  dump_file_path:
    description: 'Path to the DB dump'
    required: true
  db_name:
    description: 'DB name to export dump from'
    required: true
  host:
    description: 'MySQL server address'
    required: false
    default: 'localhost'
  username:
    description: 'MySQL server username'
    required: false
    default: 'root'
  password:
    description: 'MySQL server password'
    required: false
    default: 'root'
  port:
    description: 'MySQL port'
    required: false
    default: '3306'

runs:
  using: "composite"
  steps:
    - name: MySQL export
      run: |
        mysqlpump -u ${{inputs.username}} -p${{inputs.password}} --host ${{inputs.host}} --port ${{inputs.port}} --no-create-db --skip-definer=true ${{ inputs.db_name }} --result-file=${{ inputs.dump_file_path }}
        sed -i '/^USE `${{ inputs.db_name }}`;/d' ${{ inputs.dump_file_path }}
        sed -i '/-- Dump start time:/ {N; s/.*\n//}' ${{ inputs.dump_file_path }}   # This deletes the line with the line ending
        sed -i 's/-- Dump end time: .*//' ${{ inputs.dump_file_path }}              # This replaces the line with an empty one
        sed -i -r 's/`{0,1}${{inputs.db_name}}`{0,1}\.//g' ${{inputs.dump_file_path}}
      shell: bash
