name: 'mysql-export'

inputs:
  dump_file_path:
    description: 'Path to the DB dump'
    required: true
  db_name:
    description: 'DB name to export dump from'
    required: true
  host:
    description: 'MySQL server address'
    required: false
    default: '127.0.0.1'
  username:
    description: 'MySQL server username'
    required: false
    default: 'root'
  password:
    description: 'MySQL server password'
    required: false
    default: 'root'
  port:
    description: 'MySQL port'
    required: false
    default: '3306'

runs:
  using: "composite"
  steps:
    - name: MySQL export
      run: |
        mysqldump -q --routines --triggers --single-transaction --max_allowed_packet=512M \
          --user=${{inputs.username}} \
          --password=${{inputs.password}} \
          --host=${{inputs.host}} \
          --port=${{inputs.port}} \
          --result-file=${{ inputs.dump_file_path }} \
          ${{ inputs.db_name }}
        # Remove DEFINER from the dump 
        sed -i -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' ${{ inputs.dump_file_path }} 
        sed -i -e 's/DEFINER[ ]*=[ ]*[^*]*PROCEDURE/PROCEDURE/' ${{ inputs.dump_file_path }} 
        sed -i -e 's/DEFINER[ ]*=[ ]*[^*]*FUNCTION/FUNCTION/' ${{ inputs.dump_file_path }}
        # Remove dump end time to avoid unnecessary commits every time
        sed -i 's/-- Dump completed on .*//' ${{ inputs.dump_file_path }}
      shell: bash
