name: Spin-up application in Docker

inputs:
  docker_env_variables:
    description: 'Environment variables used for Docker config'
    required: true
    type: string
  hostname:
    description: 'Hostname to use to access application'
    required: true
    type: string
  docker_registry:
    description: 'Docker registry to log in'
    required: false
    type: string
  docker_username:
    description: 'Docker registry username'
    required: false
    type: string
  docker_password:
    description: 'Docker password/access token'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Prepare uid:gid mapping
      id: uid_gid
      run: echo "result=$(id -u):$(id -g)" >> $GITHUB_OUTPUT

    - name: Prepare environment variables for Docker
      id: merge_docker_variables
      uses: uniquesca/ci/merge-environment-variables@main
      with:
        variables1: ${{ format('{{"docker.user_map":"{0}"}}', steps.uid_gid.outputs.result) }}
        variables2: ${{ inputs.docker_env_variables }}

    - name: Prepare Docker config
      uses: uniquesca/ci/prepare-environment@main
      with:
        env_variables: ${{ steps.merge_docker_variables.outputs.variables }}
        env_file_stub: .env.dist
        env_file: .env

    - name: Update hosts file
      run: sudo echo "127.0.0.1 ${{ inputs.hostname }}" | sudo tee -a /etc/hosts

    - name: Login to Docker Hub
      if: ${{ inputs.docker_registry }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Spin up Docker
      run: docker compose up -d