name: Deploy

on:
  workflow_call:
    secrets:
      SSH_KEY:
        description: 'SSH private key to use to connect to the host'
        required: true
      UNIQUES_GITHUB_ACCESS_TOKEN:
        description: 'Access token for cloning Uniques private repositories from GitHub'
        required: true
      NODE_AUTH_TOKEN:
        description: 'Access token for authentication with the NPM registry'
        required: false
    inputs:
      host:
        description: 'Address of the server'
        required: true
        type: string
      username:
        description: 'SSH login'
        required: true
        type: string
      port:
        description: 'SSH password'
        required: false
        default: '22'
        type: string
      deployment_path:
        description: 'Working directory of the project on the server'
        required: true
        type: string
      ref:
        description: 'Git branch or tag to use for the project on the server'
        required: true
        type: string
      db_migration_cmd:
        description: 'DB migration command to execute after git update is complete'
        required: false
        default: ''
        type: string
      clean_cache_cmd:
        description: 'Command for clearing cache to execute after git update is complete'
        required: false
        default: ''
        type: string
      post_cmd:
        description: 'Command to execute after deployment is complete'
        required: false
        default: ''
        type: string
      node_version:
        description: 'Node version to use when deploying'
        required: false
        default: '20'
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Deploy Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ inputs.port }}
          script_stop: true
          script: |
            echo "Changing work dir"
            cd ${{ inputs.deployment_path }}
            
            echo "Cleaning git"
            git clean -fd
            git fetch

            # This part is commented because it doesn't work well - if there are any changes done, 
            # or some commits are ahead autodeployment will fail
            # if git show-ref -q --verify "refs/heads/${{ inputs.ref }}" 2>/dev/null; then
            #   echo "Branch detected, switching and pulling"
            #   git checkout ${{ inputs.ref }}
            #   git pull
            # else
            #   echo "Non-branch detected, performing get reset"
              git ls-remote --exit-code --heads origin ${{ inputs.ref }} >/dev/null 2>&1
              EXIT_CODE=$?

              if [[ $EXIT_CODE == '0' ]]; then
                git reset --hard origin/${{ inputs.ref }}
              else
                git reset --hard ${{ inputs.ref }}
              fi
            # fi
            
            # Improve steps here to make it possible to install things, not just update
            # mysql -u root -p root -e "CREATE DATABASE IF NOT EXISTS officio.forms;"
            
            if [ -f "composer.json" ]; then
              echo "Installing composer dependencies"
              if [ ! -f "composer.phar" ]; then
                echo "Installing Composer"
                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                php composer-setup.php
                php -r "unlink('composer-setup.php');"
              fi
              echo "Installing Composer dependencies"
              chmod +x composer.phar
              php composer.phar config --auth github-oauth.github.com ${{ secrets.UNIQUES_GITHUB_ACCESS_TOKEN }}
              php composer.phar install --no-dev
            fi
            
            if [ -f "package.json" ]; then
              echo "Preparing .npmrc file"
              echo "@uniquesca:registry=https://npm.pkg.github.com/" > .npmrc
              echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
            
              if ! command -v nvm &> /dev/null; then
                echo "Installing NVM"
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
                export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
                echo "  Using node v${{ inputs.node_version }}"
                nvm install ${{ inputs.node_version }}
                nvm alias set default ${{ inputs.node_version }}
              fi

              if ! command -v yarn &> /dev/null; then
                echo "Installing Yarn"
                nvm use default
                npm install -g yarn
              fi

              echo "Installing NPM/Yarn dependencies"
              yarn install
            fi

            if [ -f "vendor/bin/phinx" ]; then
              echo "Executing Phinx migrations"
              if [ -f "phinx.php" ]; then
                chmod +x ./vendor/bin/phinx
                chmod +x ./vendor/robmorgan/phinx/bin/phinx
                ./vendor/bin/phinx migrate -c phinx.php
                break
              fi
            fi
            
            echo "Executing DB migration command"
            ${{ inputs.db_migration_cmd }}
            
            echo "Executing cache cleaning command"
            ${{ inputs.clean_cache_cmd }}
            
            echo "Executing post-deployment command"
            ${{ inputs.post_cmd }}
