name: Prepare release

on:
  create

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    outputs:
      version: ${{ steps.get_version.outputs.version}}
    steps:
      - id: get_version
        run: |
          echo "version=$(echo ${GITHUB_REF#refs/heads/release/})" >> "$GITHUB_OUTPUT"

  pre-release:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: version
    uses: uniquesca/continuous-integration/.github/workflows/prepare-release.yml@feature/release-workflow
    secrets:
      UNIQUES_GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    with:
      version: ${{ needs.version.outputs.version }}
