name: Publish NPM package

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        description: 'Access token for authentication with the NPM registry'
        required: true
      UNIQUES_GITHUB_ACCESS_TOKEN:
        description: 'Access token for cloning Uniques private repositories from GitHub'
        required: true
    inputs:
      node_version:
        description: 'Node version to use for building and publishing the package'
        required: false
        type: number
        default: 20
      release_version:
        description: 'Version being published, has to be in x.y.z format'
        required: true
        type: string
      build_cmd:
        description: 'Command to use to build the package'
        required: false
        type: string
        default: ''
      github_release:
        description: 'Whether github release should be published too'
        required: false
        default: true
        type: boolean
      dist_folder:
        description: 'Dist folder to use for publishing'
        required: false
        default: 'dist'
        type: string
      cleanup_dependencies:
        description: 'Whether dependencies should be removed from package.json prior to publishing'
        required: false
        type: boolean
        default: false

jobs:
  publish-npm:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo "Preparing .npmrc file"
          echo "@uniquesca:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> .npmrc
          npm install

      - name: Run build command if specified
        run: ${{ inputs.build_cmd }}

      - name: Update package version
        run: |
          if [ -f "package.json" ]; then
            npm pkg set version=${{ inputs.release_version }}
          fi

      - name: Remove dependencies from package.json
        if: ${{ inputs.cleanup_dependencies == true }}
        run: |
          npm pkg delete dependencies
          npm pkg delete devDependencies
          npm pkg delete scripts

      - name: Publish NPM package on GitHub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          npm publish

        # This step is needed to prevent cleanup
      - name: Move dist repo outside of the working tree
        if: ${{ inputs.github_release == true }}
        run: cp ${{ inputs.dist_folder }} ../dist -Rf

      - name: Publish Github release
        uses: uniquesca/ci/publish-github-release@main
        if: ${{ inputs.github_release == true }}
        with:
          release_version: ${{ inputs.release_version }}
          attach_dist: true
          dist_folder: ../dist
          repo_token: ${{ secrets.UNIQUES_GITHUB_ACCESS_TOKEN }}
