name: Prepare release

on:
  create

jobs:
  version:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version}}
    steps:
      - id: get_version
        run: echo "version=$(echo ${GITHUB_REF#refs/heads/release/})" >> "$GITHUB_OUTPUT"

  pre-release:
    needs: version
    uses: ./.github/workflows/prepare-release.yml
    secrets:
      UNIQUES_GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    with:
      version: ${{ needs.version.outputs.version }}
      generate_changelog: ${{ github.event.created }}

