name: Prepare release

on:
  create

jobs:
  version:
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/get-version.yml
    with:
      ref: ${{ github.ref }}

  pre-release:
    needs: version
    uses: ./.github/workflows/prepare-release.yml
    secrets:
      UNIQUES_GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    with:
      version: ${{ needs.version.outputs.version }}
