[program:php-fpm]
command=php-fpm -F
; SIGQUIT lets php-fpm finish the requests it is serving
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
killasgroup=true
